# Generated by Django 6.0.8 on 2026-08-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
