# Generated by Django 6.0.8 on 2026-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='matrimony_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
