# Generated by Django 6.0.8 on 2026-08-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_registration_matrimony_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='disability',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='education_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='highest_education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='occupation_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='work_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='working_place',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
