# Generated by Django 6.0.8 on 2026-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_registration_disability_registration_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='about_family',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='brothers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='bus_stop',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='country_code',
            field=models.CharField(default='+91', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='extra_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='financial_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='house_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='married_brothers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='married_sisters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='post_office',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registration',
            name='relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='sisters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='taluk',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
