# Generated by Django 6.0.8 on 2026-09-10 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_profileview_interest_shortlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AddField(
            model_name='profileview',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileview',
            name='viewed_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to='registrations.registration'),
        ),
    ]
